version: '2'
exclude_patterns:
  - 'docs'
  - 'documentation'
  - 'dist'
  - '**/*.log'
  - '**/*.ico'
  - 'e2e/'
  - 'src/assets/'
  - 'src/typings.d.ts'
  - 'src/app/**/*.spec.ts'
  - 'src/karma.conf.js'
  - 'src/polyfills.ts'
  - 'src/test.ts'
